/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectChat;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.BoxLayout;
import javax.swing.JScrollPane;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Usuario
 */
public class chat extends javax.swing.JFrame {
    Socket socket;
    DataInputStream netIn;
    DataOutputStream netOut;

    /**
     * Creates new form chat
     */
    public chat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        puerto = new javax.swing.JTextField();
        ip = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        connect_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarMensajes = new javax.swing.JTextArea();
        message = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        panelContactos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre Usuario:");

        jLabel2.setText("Puerto:");

        jLabel3.setText("Dirección IP:");

        puerto.setText("1234");
        puerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertoActionPerformed(evt);
            }
        });

        ip.setText("localhost");

        connect_button.setText("Conectar");
        connect_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_buttonActionPerformed(evt);
            }
        });

        mostrarMensajes.setColumns(20);
        mostrarMensajes.setRows(5);
        jScrollPane1.setViewportView(mostrarMensajes);

        send.setText("Enviar");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContactosLayout = new javax.swing.GroupLayout(panelContactos);
        panelContactos.setLayout(panelContactosLayout);
        panelContactosLayout.setHorizontalGroup(
            panelContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContactosLayout.setVerticalGroup(
            panelContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(user))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(connect_button)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(message)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(send))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelContactos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connect_button))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(panelContactos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puertoActionPerformed

    // Conexión inicial de un usuario al chat
    private void connect_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_buttonActionPerformed
        String servidor, username;
        int puerto;
        servidor = ip.getText();
        puerto = Integer.parseInt(this.puerto.getText());
        username = user.getText();
        try {
            socket = new Socket(servidor, puerto);
            netIn = new DataInputStream(socket.getInputStream());
            netOut = new DataOutputStream(socket.getOutputStream());

            netOut.writeUTF(username);

            // Crear el hilo y pasar mostrarMensajes y panelContactos
            hilo thread = new hilo(netIn, mostrarMensajes, this);
            thread.start();
        } catch (IOException e) {
            mostrarMensajes.append("Error al conectar.\n");
        }
    }//GEN-LAST:event_connect_buttonActionPerformed

    // Enviar un mensaje
    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // Obtener el texto del campo de entrada
        String mensaje = message.getText();
        if (!mensaje.isEmpty()) {
            try {
                // Enviar el mensaje al servidor
                netOut.writeUTF(mensaje);
                // Limpiar el campo de entrada después de enviar
                message.setText("");
            } catch (IOException e) {
                // En caso de error
                mostrarMensajes.append("Error al enviar el mensaje.\n");
            }
        }
    }//GEN-LAST:event_sendActionPerformed


    // Mostrar los contactos como botones
    public void actualizarContactos(ArrayList<String> usuariosConectados) {
        // Eliminar botones anteriores
        panelContactos.removeAll();

        // Usar BoxLayout para alinear los botones verticalmente
        panelContactos.setLayout(new BoxLayout(panelContactos, BoxLayout.Y_AXIS));

        for (String usuario : usuariosConectados) {
            JButton botonUsuario = new JButton(usuario);
            botonUsuario.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Clic para abrir un chat privado
                    iniciarChatPrivado(usuario);
                }
            });
            panelContactos.add(botonUsuario);
        }

        panelContactos.revalidate(); // Actualizar el panel
        panelContactos.repaint();     // Repaint para reflejar los cambios
    }
    
    public void iniciarChatGrupal() {
        JFrame ventanaGrupal = new JFrame("Chat Grupal");
        ventanaGrupal.setSize(400, 300);

        JTextArea areaMensajes = new JTextArea();
        areaMensajes.setEditable(false);
        JTextField campoMensaje = new JTextField(20);
        JButton botonEnviar = new JButton("Enviar");

        botonEnviar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String mensaje = campoMensaje.getText();
                if (!mensaje.isEmpty()) {
                    enviarMensajeGrupal(mensaje);
                    campoMensaje.setText("");
                    areaMensajes.append("Tú: " + mensaje + "\n");
                }
            }
        });

        JPanel panelInferior = new JPanel();
        panelInferior.add(campoMensaje);
        panelInferior.add(botonEnviar);

        ventanaGrupal.add(new JScrollPane(areaMensajes), BorderLayout.CENTER);
        ventanaGrupal.add(panelInferior, BorderLayout.SOUTH);

        ventanaGrupal.setVisible(true);
    }
    
    // Método para enviar mensaje al chat grupal
    public void enviarMensajeGrupal(String mensaje) {
        try {
            netOut.writeUTF("/grupal " + mensaje);
        } catch (IOException e) {
            mostrarMensajes.append("Error al enviar mensaje grupal.\n");
        }
    }

    // Abrir una ventana de chat privado
    public void iniciarChatPrivado(String usuarioDestino) {
        JFrame ventanaPrivada = new JFrame("Chat privado con " + usuarioDestino);
        ventanaPrivada.setSize(400, 300);

        JTextArea areaMensajes = new JTextArea();
        areaMensajes.setEditable(false);
        JTextField campoMensaje = new JTextField(20);
        JButton botonEnviar = new JButton("Enviar");

        botonEnviar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String mensaje = campoMensaje.getText();
                if (!mensaje.isEmpty()) {
                    enviarMensajePrivado(usuarioDestino, mensaje);
                    campoMensaje.setText("");
                    areaMensajes.append("Tú: " + mensaje + "\n");
                }
            }
        });

        JPanel panelInferior = new JPanel();
        panelInferior.add(campoMensaje);
        panelInferior.add(botonEnviar);

        ventanaPrivada.add(new JScrollPane(areaMensajes), BorderLayout.CENTER);
        ventanaPrivada.add(panelInferior, BorderLayout.SOUTH);

        ventanaPrivada.setVisible(true);
    }

    // Enviar mensaje privado al usuario destino
    public void enviarMensajePrivado(String usuarioDestino, String mensaje) {
        try {
            netOut.writeUTF("/privado " + usuarioDestino + " " + mensaje);
        } catch (IOException e) {
            mostrarMensajes.append("Error al enviar mensaje privado.\n");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connect_button;
    private javax.swing.JTextField ip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField message;
    private javax.swing.JTextArea mostrarMensajes;
    private javax.swing.JPanel panelContactos;
    private javax.swing.JTextField puerto;
    private javax.swing.JButton send;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}